name: Build release Docker Images

on:
  push:
    tags:
      - "@agoric/sdk@*"

jobs:
  docker-godeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Save Git revision
      run: git log -1 --format='%H' > packages/cosmic-swingset/lib/git-revision.txt
    - name: Build Go dependencies image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/cosmic-swingset
        dockerfile: packages/cosmic-swingset/Dockerfile
        context: packages/cosmic-swingset
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tags: latest
  
  docker-sdk:
    needs: docker-godeps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build SDK image
      # needs agoric/cosmic-swingset:latest
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/agoric-sdk
        dockerfile: packages/deployment/Dockerfile.sdk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tags: latest

  # This is currently needed for the relayer integration test framework.
  # It just runs agoric/agoric-sdk with a "single-node" argument.
  docker-ibc-alpha:
    needs: docker-sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build ibc-alpha image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/agoric-sdk
        dockerfile: packages/deployment/Dockerfile.ibc-alpha
        context: packages/deployment/docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ibc-alpha

  docker-solo:
    needs: docker-sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build ag-solo image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/cosmic-swingset-solo
        dockerfile: packages/cosmic-swingset/lib/ag-solo/Dockerfile
        context: packages/cosmic-swingset/lib/ag-solo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tags: latest

  docker-setup:
    needs: docker-sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build setup image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/cosmic-swingset-setup
        dockerfile: packages/deployment/Dockerfile
        context: packages/deployment
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tags: latest

  docker-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build setup image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: agoric/deployment
        dockerfile: packages/deployment/Dockerfile.deployment
        context: packages/deployment/docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tags: latest
